app: gromits
service: poi-service

configValidationMode: error
variablesResolutionMode: 20210326
useDotenv: true
unresolvedVariablesNotificationMode: error

provider:
  name: aws
  region: eu-west-2
  stage: ${opt:stage}
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  usagePlan:
    quota:
      limit: 1000000
      period: MONTH
  environment:
    DB_URL: ${env:DB_URL}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}

package:
  individually: true

plugins:
  - serverless-bundle

functions:
  getBuildingsInPolygon:
    handler: src/handlers/getBuildingsInPolygonHandler.main
    events:
      - http:
          path: /buildings/polygon/
          method: get
          cors: true
  createBuilding:
    handler: src/handlers/createBuildingHandler.main
    events:
      - http:
          path: /building
          method: post
          cors: true
          request:
            schemas:
              application/json: ${file(src/schemas/building_schema.json)}

resources:
  Resources:
    ${file(resources/api-gateway-errors.yml)}