app: gromits
service: poi-service

configValidationMode: error
variablesResolutionMode: 20210326

provider:
  name: aws
  region: eu-west-2
  stage: dev
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  usagePlan:
    quota:
      limit: 1000000
      period: MONTH

plugins:
  - serverless-bundle

functions:
  app:
    handler: handler.handler
    environment:
      DB_URL: ${ssm:/poi-service-db-url}
      DB_USER: ${ssm:/poi-service-db-username}
      DB_PASS: ${ssm:/poi-service-db-password}
    events:
      - http:
          path: /buildings/{location}
          method: get
          cors: true
      - http:
          path: /buildings/polygon/
          method: get
          cors: true
