app: gromits
service: poi-service

configValidationMode: error
variablesResolutionMode: 20210326

provider:
  name: aws
  region: eu-west-2
  stage: dev
  runtime: nodejs14.x
  profile: personal
  lambdaHashingVersion: 20201221

  environment:
    DB_URL: ${param:dbUrl}
    DB_USER: ${param:dbUser}
    DB_PASS: ${param:dbPass}

plugins:
  - serverless-offline

functions:
  app:
    handler: handler.handler
    events:
      - http:
          path: /buildings/{location}
          method: get
          cors: true
      - http:
          path: /buildings/polygon/
          method: get
          cors: true
