name: Deploy landmarks-api
inputs:
  working-directory:
    description: The directory of the landmarks-api service
    required: false
    default: ${{ github.action_path }}/services/landmarks-api
  stage:
    description: The stage to which to deploy, e.g. 'development' or 'production'
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      run: npm ci
    - name: serverless deploy
      working-directory: ${{ inputs.working-directory }}
      uses: serverless/github-action@master
      with:
        args: deploy --stage ${{ input.stage }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}